import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faFileUpload,
  faFolderPlus,
  faUsers,
  faUserSlash,
  faServer,
  faSyncAlt,
  faFolderOpen,
  faHdd,
  faArrowAltCircleDown,
  faTrash,
  faArrowDown,
  faAngleLeft,
  faFile,
  faFileWord,
  faFileVideo,
  faFilePowerpoint,
  faFilePdf,
  faFileImage,
  faFileExcel,
  faFileCode,
  faFileAudio,
  faFileArchive,
  faFileAlt,
  faFileCsv,
  faFileContract,
  faFolder,
  faEllipsisV,
  faTerminal
} from '@fortawesome/free-solid-svg-icons';

export function installIcons() {

  library.add(
    faFileUpload,
    faFolderPlus,
    faUsers,
    faUserSlash,
    faServer,
    faSyncAlt,
    faFolderOpen,
    faHdd,
    faArrowAltCircleDown,
    faTrash,
    faArrowDown,
    faAngleLeft,
    faFile,
    faFileWord,
    faFileVideo,
    faFilePowerpoint,
    faFilePdf,
    faFileImage,
    faFileExcel,
    faFileCode,
    faFileAudio,
    faFileArchive,
    faFileAlt,
    faFileCsv,
    faFileContract,
    faFolder,
    faEllipsisV,
    faTerminal
  );

}
